name: CI_P5

on: [push, pull_request]

jobs:
  CompilationTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake python3 python3-pip
          pip3 install conan

      - name: Configure Conan
        run: conan profile detect

      - name: Build with Conan
        run: |
          conan install . --build=missing
          conan build . --build=missing